### ISSUE TITLE
ParallelCHOCO v.s. ParallelCHOCO_V

### ISSUE THREAD

**Issue by pursueorigin** [epfml/ChocoSGD#3]
Hi,

It's a really nice work!  But what's the difference between ParallelCHOCO and ParallelCHOCO_V?

Thanks!

**Comment by tlin-taolin** [comment]
Hi, the algorithm is the same for `ParallelCHOCO` and `ParallelCHOCO_V`. 

They only differ in the implementation details: `ParallelCHOCO` is a multiprocessing based implementation while `ParallelCHOCO_V` is based on multi-thread. The former one should be more efficient but might have some memory leakage issues.

I include these two implementations for reference purposes, and I would recommend using `ParallelCHOCO` for ResNet like architectures and `ParallelCHOCO_V` for 3-layer LSTM.

**Comment by pursueorigin** [comment]
Thanks!

Can you please give an example about how to define the hostfile? Thanks!

**Comment by tlin-taolin** [comment]
Actually I included one `hostfile` [here](https://github.com/epfml/ChocoSGD/blob/master/dl_code/hostfile). If you want to run distributed training experiment (across machines), then please change the `localhost` to your expected IPs and change the `slots` to the number of MPI processes per machine. 

For example, if you have two machines with ip1 and ip2, and each machine will allocate 1 MPI process, then the `hostfile` should be something like:
```
ip1 slots=1
ip2 slots=1
``` 

Note that the 1 MPI process can use `dataparallel` locally with multiple GPUs, by specifying `n_sub_process`.

**Comment by pursueorigin** [comment]
If I have the following setting, does it mean there are two MPI processes in one machine and each process uses one GPU? 

n_mpi_process=2, n_sub_process=1 and world=0,1

localhost slots=2

**Comment by tlin-taolin** [comment]
yes. exactly.

**Comment by pursueorigin** [comment]
Thanks!
