### ISSUE TITLE
Hi, could you please provide more detailed information about the environment, like how to deploy kubernetes?

### ISSUE THREAD

**Issue by wizard1203** [epfml/ChocoSGD#5]
Hi, could you please provide more detailed information about the environment, like how to deploy kubernetes?

**Comment by tlin-taolin** [comment]
Hi, thank you for your interest!

Please use our provided [dockerfiles](https://github.com/epfml/ChocoSGD/tree/master/dl_code/environments/docker) to build the required docker images.

Regarding the Kubernetes deployment, please make sure you have an available Kubernetes cluster, and then you can e.g. refer to [our repo](https://github.com/epfml/kubernetes-setup) for a brief intro.
