### ISSUE TITLE
Hi, is this a bug in codes?

### ISSUE THREAD

**Issue by wizard1203** [epfml/ChocoSGD#6]
In this line  _https://github.com/epfml/ChocoSGD/blob/3cb976a54499c2cdc8ea68e001217b42b58870ae/dl_code/run.py#L98_, the task_scripts=[_tasks] transmits the variable _tasks into _https://github.com/epfml/ChocoSGD/blob/3cb976a54499c2cdc8ea68e001217b42b58870ae/dl_code/tmux_cluster/tmux.py#L28_, so the len(task_scripts) should always be 1. So I guess there will be some bugs _https://github.com/epfml/ChocoSGD/blob/3cb976a54499c2cdc8ea68e001217b42b58870ae/dl_code/tmux_cluster/tmux.py#L41._

**Comment by tlin-taolin** [comment]
Hi, the `len(task_scripts)` should equal to 1, as for each IP (i.e. node), it will only initialize one process. It is an adapted usage of the `tmux.py`. So I think it is not a bug.

BTW, by default, we do not use this functionality (though we provided them here); the `remote_exec ` is our use case is always equal to `False`, i.e. line 93 of `run.py` will be executed.

**Comment by wizard1203** [comment]
Thank you!
If I want to use multiple remote machines, maybe I need to change some codes here.

**Comment by tlin-taolin** [comment]
I think it somehow depends on the communication backend you want to use.

These remote execution code snippets were used for my personal NCCL backend usage (that is why for each node/IP, I only initialize one process). 

If you can use MPI backend, I think a more convenient way could be: configure your `hostfile` with the IPs of your remote machines and change the lines in `run.py` a bit by only initializing the MPI task on one of your nodes (the code of `tmux_cluster` should not be modified).

**Comment by wizard1203** [comment]
@IamTao Got it. Thank you for the detailed explanation !

**Comment by guochengqian** [comment]
hi, @IamTao 
May I ask why people tend to use MPI instead of NCCL? Seems PyTorch strongly suggests using NCCL instead. Plus, seems NCCL is more for GPU-GPU communication and MPI is more for CPU-CPU communication? 

do you have any plan supporting NCCL?

**Comment by tlin-taolin** [comment]
Hi, the reason why we choose MPI instead of the NCCL, is mainly due to the supported communication operations, as you can find them in this [link](https://pytorch.org/docs/stable/distributed.html). 
It is more flexible to use `send` and `recv` operations, supported by the MPI backend (built from source with CUDA support), for research on decentralized deep learning.
