### ISSUE TITLE
Is there a minimal ratio that can guarantee convergence with Sparsification method?

### ISSUE THREAD

**Issue by Ethanwl** [epfml/ChocoSGD#7]
In Table 1, the minimal compression ratio is 0.01. Can the compression ratio be reduced further? Is there a minimal ratio that can guarantee accuracy not drop too much?

**Comment by tlin-taolin** [comment]
Sorry for the missed message.

We only tested the commonly used sparsity ratio 99% and our CHOCO outperforms existing methods.
The sparsity ratio of course can be further increased, e.g. to 99.9% as in DGC; but we did not examine the extreme cases.
