### ISSUE TITLE
Possible bug in initializing torus topology

### ISSUE THREAD

**Issue by arjunarao619** [epfml/ChocoSGD#9]
In `utils/topology.py` for the `TorusGraph` class, the mixing matrix is initialized as:

```
for i in range(0, mixing_matrix.shape[0]):            
  mixing_matrix[i][i] = 1        
mixing_matrix = mixing_matrix / 5  
return mixing_matrix
```
However, `mixing_matrix = mixing_matrix / 5` doesn't produce doubly stochastic matrices. For example, for n=4 nodes, [this](https://imgur.com/x7H2r8i) is the mixing matrix.

A simple fix could probably be:

```
rows = (mixing_matrix != 0).sum(1)
mixing_matrix = mixing_matrix/rows[0]
return mixing_matrix
```

**Comment by tlin-taolin** [comment]
thanks for the feedback (updated it accordingly)
